# Generated by Django 4.2.7 on 2023-12-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_unique_product_name_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created_at',)},
        ),
    ]
