# Generated by Django 4.2.7 on 2023-12-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
