# Generated by Django 4.2.7 on 2023-12-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_for_sale'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_name_owner',
        ),
    ]
