# Generated by Django 4.2.7 on 2023-12-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_name_owner',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_owner',
            new_name='owner_id',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'owner_id'), name='unique_product_name_owner'),
        ),
    ]
