# Generated by Django 4.2.7 on 2023-12-10 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_owner',
            new_name='owner',
        ),
    ]
