# Generated by Django 4.2.7 on 2023-11-30 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name_owner',
        ),
    ]
