# Generated by Django 4.2.7 on 2023-12-10 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_rename_category_owner_category_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
