# Generated by Django 4.2.7 on 2023-12-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_name_unitsuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitsuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
